apiVersion: v1
kind: Pod
metadata:
  name: huge-request-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "100"        # 100 CPUs
        memory: "128Gi"   # 128 GiB RAM