version: "3.9"

services:
  mysql:
    image: mysql
    container_name: my-mysql
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_ROOT_PASSWORD: rootpass
    env_file:
      - path: ./mysql.env
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-net
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  wordpress:
    image: wordpress:latest
    container_name: wordpress-container
    ports:
        - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
    env_file:
      - path: ./wp.env
    restart: always
    networks:
      - wp-net
    volumes:
      - wp-data:/var/www/html

volumes:
  db_data:
  wp-data:
networks:
    wp-net:
      driver: bridge

